src/event_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]

src/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='home'
urlpatterns = [
    path('test2/', views.index,name='index'),
    path('test2/login',views.logins,name='login'),
    path('test2/logout',views.logouts,name='logout'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

src/home/models.py
from django.db import models

# Create your models here.

# class Video(models.Model):
#     image_url = models.FileField(_(""), upload_to=None, max_length=100)

src/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.conf import settings
import os
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import event_detection.settings as settings
from django.contrib.auth import authenticate, login, logout
from detector.c3d import *
from detector.classifier import *
from detector.utils.visualization_util import *
import numpy as np
import tensorflow as tf
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

# Create your views here.
# demo.run_demo()
@csrf_exempt
def index(request):
    if request.method == "POST":
        try:
            # print(request.url)
            myfile = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            
            uploaded_file_url = os.path.join(settings.BASE_DIR, 'media', filename)

            start,end=0,0
            start, end = run_demo(uploaded_file_url)
            if start==0 and end==0:
                message = {
                    'status':False,
                    'message':"No activity detected",
                    'start':start,
                    'end':end 
                }
            else:
                 message = {
                    'url': fs.url(filename),
                    'status':True,
                    'message':"Unusual Activity Detected",
                    'start':start,
                    'end':end
                }
            return JsonResponse(message)
        except:
            message = {
                'status':False,
                'message':"Processing Error",
            }
            return JsonResponse(message)

    return render(request,'home/upload_video.html',context={})

def run_demo(video_path):
    video_name = os.path.basename(video_path).split('.')[0]
    video = cv2.VideoCapture(video_path)
    fps = video.get(cv2.CAP_PROP_FPS)
    # read video
    video_clips, num_frames = get_video_clips(video_path)

    print("Number of clips in the video : ", len(video_clips))

    # build models

    print("Models initialized")
    feature_extractor = c3d_feature_extractor()
    classifier_model = build_classifier_model()
    # extract features
    rgb_features = []
    for i, clip in enumerate(video_clips):
            clip = np.array(clip)
            if len(clip) < params.frame_count:
                continue
            clip = preprocess_input(clip)
            
            # set_session(sess)
            rgb_feature = feature_extractor.predict(clip)[0]
            rgb_features.append(rgb_feature)

            print("Processed clip : ", i)

    rgb_features = np.array(rgb_features)

    # bag features
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
    print("Interpolation Done")

    # classify using the trained classifier model
    predictions = classifier_model.predict(rgb_feature_bag)
    print("Classification Done")
    predictions = np.array(predictions).squeeze()
    print("Predictions Squeezed")
    predictions = extrapolate(predictions, num_frames)
    print("Predictions Extrapolated")
    start, end = 0, 0
    for p in range(len(predictions)):
        if(predictions[p] >= 0.05):
            start = p
            break
    for p in range(len(predictions)-1, -1, -1):
        if(predictions[p] >= 0.05):
            end = p
            break
    start = int(start/fps)
    end = int(end/fps)
    print(start, end)
    # print(predictions)
    save_path = os.path.join(cfg.output_folder, video_name + '.gif')
    # np.savetxt('data.csv',predictions,delimiter=',')
    # visualize predictions
    # visualize_predictions(cfg.sample_video_path, predictions, save_path)
    print("GIF saved")
    return start,end

def logins(request):
    # logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home:index'))
        
        return  HttpResponseRedirect(reverse('home:index'))

def logouts(request):
    logout(request)
    return  HttpResponseRedirect(reverse('home:index'))

src/home/templates/home/index.html
<!DOCTYPE html>
<html>

<body>

    <h1>jQuery Ajax submit Multipart form</h1>

    <form method="POST" enctype="multipart/form-data" id="fileUploadForm">
        <input type="text" name="extraField" /><br /><br />
        <input type="file" name="video_upl" /><br /><br />
        <input type="file" name="files" /><br /><br />
        <input type="submit" value="Submit" id="btnSubmit" />
    </form>

    <h1>Ajax Post Result</h1>
    <span id="result"></span>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script>
        $(document).ready(function () {

        $("#btnSubmit").click(function (event) {

        //stop submit the form, we will post it manually.
        event.preventDefault();

        // Get form
        var form = $('#fileUploadForm')[0];

        // Create an FormData object
        var data = new FormData(form);

        // If you want to add an extra field for the FormData
        data.append("CustomField", "This is some extra data, testing");

        // disabled the submit button
        $("#btnSubmit").prop("disabled", true);
         console.log(data);   
        $.ajax({
        type: "POST",
        enctype: 'multipart/form-data',
        url: "/test2/",
        data: data,
        processData: false,
        contentType: false,
        cache: false,
        timeout: 600000,
        success: function (data) {

        $("#result").text(data);
        console.log("SUCCESS : ", data);
        $("#btnSubmit").prop("disabled", false);

        },
        error: function (e) {

        $("#result").text(e.responseText);
        console.log("ERROR : ", e);
        $("#btnSubmit").prop("disabled", false);

        }
        });

        });

        });
    </script>

</body>

</html>

src/home/templates/home/upload_video.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>Unusual Activity Detection</title>
    <meta name="description" content=""/>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"/> -->
    <link rel="stylesheet" href="{% static 'home/video-js.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'home/videojs.markers.min.css' %}"/>
    <script src="{% static 'home/jquery-2.0.3.min.js' %}"></script>
    <script src="{% static 'home/video.min.js' %}"></script>
    <script src="{% static 'home/videojs-markers.min.js' %}"></script>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <title>Upload video</title>
  <style type="text/css">
  	body{
  		background-image: url("{% static 'home/cybersecurity.jfif' %} ");
      padding-bottom: 400px;
      background-size: cover;
  	}
  	/* .container{
  		 transform: translate(25%,40%);
  	} */
  </style>
</head>

<body style="overflow-x: hidden;">
	<nav id="navbar" style = "border-radius: 0 0 7px 7px;" class="navbar navbar-dark bg-primary">
		<ul class="navbar-nav ml-auto">
        <li style="color:white;" class="nav-item active">{{request.user.username}}</li>
    		<li class="nav-item active">
       {% if request.user.is_authenticated %}
				<a class="navbar-brand trigger-btn"  href="{% url 'home:logout' %}">Logout</a>
        {% else %}
				<a class="navbar-brand trigger-btn" data-toggle="modal" href="#myModal">Login</a>
        {% endif %}
			</li>
		</ul>
	</nav>
<!-- Modal HTML -->
<div id="myModal" class="modal fade">
  <div class="modal-dialog modal-login">
    <div class="modal-content">
      <div class="modal-header">        
        <h4 class="modal-title">Sign In</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <form action="{% url 'home:login' %}" method="post">
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user"></i></span>
              <input type="text" class="form-control" name="username" placeholder="Username" required="required">
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
              <input type="password" class="form-control" name="password" placeholder="Password" required="required">
            </div>
          </div>
          {% csrf_token %}
          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Sign In</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>     

{% if request.user.is_authenticated %}
  <div class="container">
    <div id='trial' style="width: fit-content; position: absolute;top:50%;left: 50%; margin-bottom: 150px; transform: translate(-50%,-50%);">
      <center>
    <div class="row text-center">
      <div class="col">

        <div class="mb-3 mt-3">

          <h2 class="mb-3" style="color:white; font-weight: 300">Upload Surveillance Video</h2>

          <div class="form-group mb-3">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="file" id="file_input" oninput="input_filename();">
              <label style="text-align: left;" id="file_input_label" class="custom-file-label" for="image">Select Video file</label>
            </div>
          </div>

          <button onclick="upload('/test2/');" id="upload_btn" class="btn btn-primary">Upload</button>

          <button class="btn btn-primary d-none" id="loading_btn" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Processing...
          </button>

          <button type="button" id="cancel_btn" class="btn btn-secondary d-none">Cancel upload</button>

        </div>

        <div id="progress_wrapper" class="d-none">
          <label style="color:white;" id="progress_status"></label>
          <div class="progress mb-3">
            <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>

        <div id="alert_wrapper"></div>

        <center>
          <h4 id="duration" style="color:white"></h4>
          <div id="vid"></div>
        </center>
      </div>
       </center>
    </div>
  {% else %}
    <center><h1 style="color:white">Login Required</h1></center>
  {% endif %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
  <!-- Import Bootstrap JavaScript here -->
  
  <script type="text/javascript" src="{% static 'home/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>